version: '3.7'

services:
  
  ldap_manager:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    # depends_on:
    #   - openldap
    #command: /start
    command: python manage.py runserver 0.0.0.0:7000

# networks: 
#   default: 
#     external: 
#       name: openldap2_organization